# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-05 18:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Logdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_req', models.TextField(verbose_name='Post to API, via request (python)')),
                ('post_curl', models.TextField(verbose_name='Post to API, via curl (CLI)')),
            ],
            options={
                'verbose_name': 'Log Post',
                'verbose_name_plural': 'Logs Posts',
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo', models.CharField(max_length=20, unique=True, verbose_name='Número')),
                ('dados_processo', models.TextField(verbose_name='Dados')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
            },
        ),
    ]
